# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 215caff0b0ea92e24a4f6969b2465519bbc12cfe276bf9ed354a75752f40ba9c57a991367446911d117987a2098409ddd1da3c046ee9d1cd392400b8e60bda53

test:
  domain_name: example.com 
  secret_key_base: b21cd3968a00e19392492f73d8994bbbef124b745fb92b5996b45ceaf83030481b41444bc895952af5a00dd943eed7db825d90c1fb78b2fd37b5b1043d58b470

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
